steps:
- powershell: |
   $var = (gci env:*).GetEnumerator() | Sort-Object Name
   $out = ""
   Foreach ($v in $var) {$out = $out + "`t{0,-28} = {1,-28}`n" -f $v.Name, $v.Value}
   
   $timestamp = $(get-date -f yyyyMMddHHmmss)

   write-output "dump variables on $env:BUILD_ARTIFACTSTAGINGDIRECTORY/build_variables_dump_$timestamp.md"
   $fileName = "$env:BUILD_ARTIFACTSTAGINGDIRECTORY/build_variables_dump_$timestamp.md"
   set-content $fileName $out

   write-output "##vso[task.addattachment type=Distributedtask.Core.Summary;name=Environment Variables $timestamp;]$fileName"

  errorActionPreference: continue
  displayName: 'Dump build variables'
  condition: succeededOrFailed()