{{#if variable-groups}}
variables :
{{#each variable-groups}}
- group: {{{this}}}
{{/each}}
{{/if}}

{{{branch-triggers}}}

{{{pr-triggers}}}

#
# Jobs
#
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=vsts&tabs=yaml

jobs:

{{#each jobs}}
{{{this}}}


{{/each}}